[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'Cryptid.profile_prefix = "M"'
position = "after"
payload = 'Cryptid.profile_prefix = Cryptid.profile_prefix == "M" and "T" or Cryptid.profile_prefix.."T"'
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'Cryptid.profile_prefix = Jen and "J" or "M"'
position = "after"
payload = 'Cryptid.profile_prefix = Cryptid.profile_prefix == "M" and "T" or Cryptid.profile_prefix.."T"'
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = 'G.viewed_stake = G.viewed_stake or 1'
position = "after"
payload = 'G.viewed_stake = G.viewed_stake or G.tower_default_stake or 1'
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = 'G.viewed_stake = G.viewed_stake or 1'
position = "after"
payload = 'G.viewed_stake = G.viewed_stake or G.tower_default_stake or 1'
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "function localize(args, misc_cat)"
position = "after"
payload = '''
if args == nil and misc_cat == "ranks" then
    args = "tower_Joker"
end
if args == nil and misc_cat == "suits_plural" then
    args = "tower_Joker"
end
if args == nil and misc_cat == "suits_singular" then
    args = "tower_Joker"
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "for k, v in ipairs(G.playing_cards) do"
position = "after"
payload = '''if v.ability.set == "Joker" then 
	local options = {}
	for i, v in pairs(SMODS.Suits) do
		options[#options+1] = i
	end
	v.base.suit = pseudorandom_element(options, pseudoseed("tower_whatsuithuh"))
	options = {}
	for i, v in pairs(SMODS.Ranks) do
		options[#options+1] = i
	end
	v.base.value = pseudorandom_element(options, pseudoseed("tower_whatrankhuh"))
	v.ability.tower_is_temp = true
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "local v_nr, v_ns = SMODS.has_no_rank(v), SMODS.has_no_suit(v)"
position = "after"
payload = '''if v.ability.set == "Joker" then 
	v_nr = true; v_ns = true
end'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """if highest_win >= G.P_STAKES["stake_red"].stake_level then
            unlock_achievement('low_stakes')
        end
        if highest_win >= G.P_STAKES["stake_black"].stake_level then
            unlock_achievement('mid_stakes')
        end
        if highest_win >= G.P_STAKES["stake_gold"].stake_level then
            unlock_achievement('high_stakes')
        end"""
position = "at"
payload = '' # achievments existing cause crash
match_indent = true