[manifest]
version = "1.0.0"
dump_lua = true
priority = -9

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''local scaling_responses = {}'''
position = "after"
payload = '''
for _, _card in ipairs(G.fortunes) do
    local obj = _card.config.center
    if obj.calc_scaling and type(obj.calc_scaling) == "function" then
        local ret = obj:calc_scaling(_card, card, initial, scalar_value, args)
        if ret then
            if ret.override_value and not args.block_overrides.value then initial = ret.override_value.value; SMODS.calculate_effect(ret.override_value, _card) end
            if ret.override_scalar_value and not args.block_overrides.scalar then scalar_value = ret.override_scalar_value.value; SMODS.calculate_effect(ret.override_scalar_value, _card) end
            if ret.override_message and not args.block_overrides.message then scaling_message = SMODS.merge_defaults(ret.override_message, scaling_message) end
            if ret.post then ret.post.source = _card; scaling_responses[#scaling_responses + 1] = ret.post end
            SMODS.calculate_effect(ret, _card)
        end
    end
end
'''
match_indent = true

